version: '1'
services:
  redis:
    build: ./redis/
    container_name: holy-grail-redis
    restart: unless-stopped
    ports: 
      - "6379:6379"
    expose:
      - 6379
  app:
    depends_on:
      - holy-grail-redis
    build: ./app/
    container_name: holy-grail-app
    restart: unless-stopped
